"""create user and order tables

Revision ID: 2c64858d8bf1
Revises: 
Create Date: 2024-07-23 12:15:44.800918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '2c64858d8bf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ORDER_STATUS = (
        ('PENDING', 'pending'),
        ('IN-PROGRESS', 'in-progress'),
        ('DELIVERED', 'delivered')
    )

PIZZA_SIZES = (
    ('SMALL', 'small'),
    ('MEDIUM', 'medium'),
    ('LARGE', 'large'),
    ('EXTRA-LARGE', 'extra-large')
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('is_staff', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_status', sqlalchemy_utils.types.choice.ChoiceType(choices=ORDER_STATUS), server_default='PENDING', nullable=True),
    sa.Column('pizza_size', sqlalchemy_utils.types.choice.ChoiceType(choices=PIZZA_SIZES), server_default='SMALL', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
